### ISSUE TITLE
[dnspython] File "/Library/Python/2.7/site-packages/dns/resolver.py", line 184, in __len__

### ISSUE THREAD

**Issue by nixawk** [nixawk/idns#5]
```
$ python bruteforce_domain_tld.py
....
....
{'google.com.vn': {'A': ['93.46.8.89']}}
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/gevent-1.1rc5-py2.7-macosx-10.11-intel.egg/gevent/greenlet.py", line 522, in run
    result = self._run(*self.args, **self.kwargs)
  File "/Users/Open-Security/Code/idns/idns/worker.py", line 120, in main_child
    self.fake_job()
  File "bruteforce_domain_tld.py", line 23, in fake_job
    data = self.query_A(subdomain)[subdomain]['A']
  File "/Users/Open-Security/Code/idns/idns/idns.py", line 91, in query_A
    if _.rdtype == dns.rdatatype.A] if resp else []
  File "/Library/Python/2.7/site-packages/dns/resolver.py", line 184, in __len__
    return len(self.rrset)
TypeError: object of type 'NoneType' has no len()
<Greenlet at 0x100b77370: <bound method idns_bruteforce.main_child of <__main__.idns_bruteforce object at 0x10099d3d0>>(<function _inner at 0x100b71320>)> failed with TypeError

{'google.com.yt': {'A': []}}
```

**Comment by nixawk** [comment]
If an issue in your lab, please update **dnspython**.

```
$ sudo pip install -U dnspython
```
